### ISSUE TITLE
Black Screen on launch

### ISSUE THREAD

**Issue by Damgam** [EvolutionRTS/EvoRTS-Chobby#1]
[infolog.txt](https://github.com/EvolutionRTS/EvoRTS-Chobby/files/3444355/infolog.txt)

**Comment by gajop** [comment]
On launch of what? This infolog doesn't seem related to Chobby..

**Comment by ScarylePoo** [comment]
Upon chobby launch. Chobby runs spring. Spring shows black screen when running chobby via the launcher. I've run into it when launching Evo, BA, BAR, and chobby. Usually deleting springsettings fixes it, however, in damgam's case, he has tried that and it doesn't work.

**Comment by gajop** [comment]
Doesn't seem related to this infolof though. @Damgam Please upload a proper infolog, it's probably a Lua error like in Forbs case

**Comment by gajop** [comment]
Old-launcher/broken install issue
See https://github.com/Spring-Chobby/Chobby/issues/476
